import type { Config } from "tailwindcss";

export default {
  darkMode: 'class',
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      'xs': '480px',
      'sm': '640px',
      'md': '768px',
      'lg': '992px',
      'xl': '1200px',
      'xxl': '1440px',
    },
    colors: {
      'primary': 'var(--color-primary)',
      'secondary': 'var(--color-secondary)',
      'thirdary': 'var(--color-thirdary)',
      'white': 'var(--color-white)',
      'warning': 'var(--color-orange-default)',
      'success': 'var(--color-green-default)',
      'error': 'var(--color-red-default)',
      'accent-content': '#A0A1A3',
      'brown': {
        DEFAULT: 'var(--color-brow-default)',
        50: 'var(--color-brow-50)',
        100: 'var(--color-brow-100)',
        200: 'var(--color-brow-200)',
        300: 'var(--color-brow-300)',
        400: 'var(--color-brow-400)',
        600: 'var(--color-brow-600)',
        700: 'var(--color-brow-700)',
        800: 'var(--color-brow-800)',
        900: 'var(--color-brow-900)',
      },
      'grey': {
        DEFAULT: 'var(--color-grey-default)',
        50: 'var(--color-grey-50)',
        100: 'var(--color-grey-100)',
        200: 'var(--color-grey-200)',
        300: 'var(--color-grey-300)',
        400: 'var(--color-grey-400)',
        600: 'var(--color-grey-600)',
        700: 'var(--color-grey-700)',
        800: 'var(--color-grey-800)',
        900: 'var(--color-grey-900)',
      },
      'red': {
        DEFAULT: 'var(--color-red-default)',
        50: 'var(--color-red-50)',
        100: 'var(--color-red-100)',
        200: 'var(--color-red-200)',
        300: 'var(--color-red-300)',
        400: 'var(--color-red-400)',
        600: 'var(--color-red-600)',
        700: 'var(--color-red-700)',
        800: 'var(--color-red-800)',
        900: 'var(--color-red-900)',
      },
      'orange': {
        DEFAULT: 'var(--color-orange-default)',
        50: 'var(--color-orange-50)',
        100: 'var(--color-orange-100)',
        200: 'var(--color-orange-200)',
        300: 'var(--color-orange-300)',
        400: 'var(--color-orange-400)',
        600: 'var(--color-orange-600)',
        700: 'var(--color-orange-700)',
        800: 'var(--color-orange-800)',
        900: 'var(--color-orange-900)',
      },
      'green': {
        DEFAULT: 'var(--color-green-default)',
        50: 'var(--color-green-50)',
        100: 'var(--color-green-100)',
        200: 'var(--color-green-200)',
        300: 'var(--color-green-300)',
        400: 'var(--color-green-400)',
        600: 'var(--color-green-600)',
        700: 'var(--color-green-700)',
        800: 'var(--color-green-800)',
        900: 'var(--color-green-900)',
      },
      'blue': {
        DEFAULT: 'var(--color-blue-default)',
        50: 'var(--color-blue-50)',
        100: 'var(--color-blue-100)',
        200: 'var(--color-blue-200)',
        300: 'var(--color-blue-300)',
        400: 'var(--color-blue-400)',
        600: 'var(--color-blue-600)',
        700: 'var(--color-blue-700)',
        800: 'var(--color-blue-800)',
        900: 'var(--color-blue-900)',
        950: 'var(--color-blue-950)',
      },
      'stone': {
        DEFAULT: 'var(--color-stone-default)',
        50: 'var(--color-stone-50)',
        100: 'var(--color-stone-100)',
        200: 'var(--color-stone-200)',
        300: 'var(--color-stone-300)',
        400: 'var(--color-stone-400)',
        600: 'var(--color-stone-600)',
        700: 'var(--color-stone-700)',
        800: 'var(--color-stone-800)',
        900: 'var(--color-stone-900)',
        950: 'var(--color-stone-950)',
      }
    },
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 1.5s ease-in-out forwards',
      },
      fontFamily: {
        sans: ['Kanit', 'sans-serif']
      },
      fontWeight: {
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
    },
  },
  plugins: [],
} satisfies Config;
